import * as React from "react";
import Container from "@mui/material/Container";
import Typography from "@mui/material/Typography";
import Box from "@mui/material/Box";
import Copyright from "@/components/Copyright";

const faqData = [
  {
    name: "General Questions",
    questions: [
      {
        name: "What does this site do?",
        text: "This site allows you to generate a command file to shut down or restart your computer. You can customize the action, operating system, and schedule, then download the file in a format appropriate for your OS.",
      },
      {
        name: "Is it safe to use these files on my computer?",
        text: "Yes, the files only contain commands to perform the selected action. You can verify this yourself by opening the file with any text editor.",
      },
      {
        name: "How does the tool determine the time zone for scheduling?",
        text: "The file is created based on the time zone set in your browser. Ensure your browser reflects the correct time zone for accurate scheduling.",
      },
      {
        name: "Are the commands different for various versions of Windows?",
        text: "No, the commands are the same for Windows Vista, 7, 8, 8.1, 10, and 11. The tool generates a universal command compatible across these versions.",
      },
    ],
  },
  {
    name: "File Formats",
    questions: [
      {
        name: "What is a .command file?",
        text: "A .command file is a script used on macOS to execute shell commands.",
      },
      {
        name: "What is a .bat file?",
        text: "A .bat file is a batch script used on Windows to execute commands in the Command Prompt.",
      },
      {
        name: "How do I run these files?",
        text:
          "macOS: Double-click the .command file. If it doesn't run, ensure it has executable permissions using chmod +x filename.command in the terminal.\n" +
          "Windows: Double-click the .bat file.",
      },
      {
        name: 'What does the "Command" field show?',
        text: "The 'Command' field displays the command generated based on your selected settings. You can edit the command directly in this field before saving or copying it.",
      },
      {
        name: 'Can I modify the file name generated in the "Command" field?',
        text: "Yes, the file name in the 'Command' field updates automatically based on your settings. However, you can edit the name manually before saving.",
      },
    ],
  },
  {
    name: "Troubleshooting",
    questions: [
      {
        name: "My file doesn’t execute. What should I do?",
        text:
          "macOS: Check if the file has the necessary executable permissions. Use chmod +x filename.command to fix this.\n" +
          "Windows: Ensure your system allows batch files to run, and check for any antivirus or security software blocking it.",
      },
      {
        name: "Why does my antivirus warn me about these files?",
        text: "Some antivirus programs flag executable files as a precaution. Rest assured, the files generated by this tool are safe.",
      },
      {
        name: "The scheduled action doesn’t work. What might be wrong?",
        text: "Ensure your computer’s clock and time zone settings are correct. Also, check for any permissions or user account control restrictions.",
      },
    ],
  },
  {
    name: "Privacy and Security",
    questions: [
      {
        name: "Are my inputs saved or stored?",
        text: "No, the site does not store any data you enter. All command files are generated locally in your browser.",
      },
      {
        name: "Can I review the contents of the generated file?",
        text: "Yes, you can open the file with a text editor to review its contents before running it.",
      },
    ],
  },
  {
    name: "Customization and Functionality",
    questions: [
      {
        name: "How can I specify the timing of the action?",
        text: "You can: \n- Choose one of the preset time values.\n- Select a specific date and time.\n- Enter a custom delay in minutes or seconds.",
      },
      {
        name: 'What does the "Forced" option do?',
        text: "The 'Forced' option forcibly terminates all running programs without giving them a chance to save data or warn you. Use this option carefully to avoid data loss.",
      },
    ],
  },
];

export default function FAQ() {
  return (
    <Container maxWidth="lg">
      <Box
        sx={{
          my: 4,
          display: "flex",
          flexDirection: "column",
          justifyContent: "center",
        }}
      >
        {faqData.map((item) => {
          return (
            <>
              <Typography variant="h4" component="h1" sx={{ mb: 2 }}>
                {item.name}
              </Typography>
              <Box sx={{ mb: 4 }}>
                {item.questions.map((question) => (
                  <>
                    <Typography variant="h6" component="div">
                      {question.name}
                    </Typography>
                    <Typography component="p" sx={{ mb: 2 }}>
                      {question.text}
                    </Typography>
                  </>
                ))}
              </Box>
            </>
          );
        })}
        {/*<Typography variant="h4" component="h1" sx={{ mb: 2 }}>*/}
        {/*  Material UI - Next.js example in TypeScript*/}
        {/*</Typography>*/}
        {/*<Box sx={{ maxWidth: "sm" }}>*/}
        {/*  <Button variant="contained" component={Link} href="/">*/}
        {/*    Go to the home page*/}
        {/*  </Button>*/}
        {/*</Box>*/}
        {/*<ProTip />*/}
        <Copyright />
      </Box>
    </Container>
  );
}
